security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\User: bcrypt
        #FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER,ROLE_ADMIN]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                success_handler: app.login_success_handler
        #secured_area:
            logout:
                path:   /logout
                target: /login

                #invalidate_session: false
                #delete_cookies:
                #    a: { path: null, domain: null }
                #    b: { path: null, domain: null }
            anonymous: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/registration, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_SUPER_ADMIN}
        - { path: ^/admin_setting, role: ROLE_ADMIN}
        - { path: ^/admin_setting/, role: ROLE_ADMIN}
        - { path: ^/upload_file_index, role: ROLE_ADMIN}
        - { path: ^/upload_file_setting, role: ROLE_ADMIN}
        - { path: ^/upload_file_delete, role: ROLE_ADMIN}
