services:
    app.userdashboard:
        class: AppBundle\Controller\AdminController
#    user.example:
#        class: UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
